### ISSUE TITLE
Bug when installing a new Paperspace instance

### ISSUE THREAD

**Issue by mikaelmorvan** [PierreBeucher/cloudypad#56]
Hi Pierre,

There's a bug when I try to install a new instance on Paperspace. I've got the last version of Cloudypad.

The logs :
Install NVIDIA driver...
  steam-paperspace failed | msg: non-zero return code | stdout: Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 535.183.01........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Welcome to the NVIDIA Software Installer for Unix/Linux

Detected 8 CPUs online; setting concurrency level to 8.
Installing NVIDIA driver version 535.183.01.
An alternate method of installing the NVIDIA driver was detected. (This is usually a package provided by your distributor.) A driver installed via that method may integrate better with your system than a driver installed by nvidia-installer.

Please review the message provided by the maintainer of this alternate installation method and decide how to proceed:

The NVIDIA driver provided by Ubuntu can be installed by launching the "Software & Updates" application, and by selecting the NVIDIA driver from the "Additional Drivers" tab.

(Answer: Continue installation)
For some distributions, Nouveau can be disabled by adding a file in the modprobe configuration directory.  Would you like nvidia-installer to attempt to create this modprobe file for you? (Answer: No) | stderr:
ERROR: The Nouveau kernel driver is currently in use by your system.  This driver is incompatible with the NVIDIA driver, and must be disabled before proceeding.  Please consult the NVIDIA driver README and your Linux distribution's documentation for details on how to correctly disable the Nouveau kernel driver.

ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

- Play recap -
  steam-paperspace           : ok=30   changed=13   unreachable=0    failed=1    rescued=0    ignored=1
2024-09-16 12:43:52.929	ERROR	/dist/src/tools/ansible.js:18	AnsibleClient	Ansible run failure: {"status":2,"signal":null,"output":[null,null,null],"pid":17,"stdout":null,"stderr":null}
/cloudypad/dist/src/tools/ansible.js:19
            throw new Error(`Ansible run failed, exit code ${ansibleProcess.status}`);
                  ^

Error: Ansible run failed, exit code 2
    at AnsibleClient.runAnsible (/cloudypad/dist/src/tools/ansible.js:19:19)
    at AnsibleConfigurator.configure (/cloudypad/dist/src/configurators/ansible.js:79:23)
    at PaperspaceInstanceInitializer.runConfiguration (/cloudypad/dist/src/core/initializer.js:67:28)
    at PaperspaceInstanceInitializer.initializeInstance (/cloudypad/dist/src/core/initializer.js:109:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.16.0

**Comment by mikaelmorvan** [comment]
The content of the file '/var/log/nvidia-installer.log'
Hope it will help you

nvidia-installer log file '/var/log/nvidia-installer.log'
creation time: Mon Sep 16 12:43:52 2024
installer version: 535.183.01

PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

nvidia-installer command line:
    ./nvidia-installer
    --no-questions
    --ui=none

Using built-in stream user interface
-> Detected 8 CPUs online; setting concurrency level to 8.
-> Installing NVIDIA driver version 535.183.01.
-> An alternate method of installing the NVIDIA driver was detected. (This is usually a package provided by your distributor.) A driver installed via that method may integrate better with your system than a driver installed by nvidia-installer.

Please review the message provided by the maintainer of this alternate installation method and decide how to proceed:

The NVIDIA driver provided by Ubuntu can be installed by launching the "Software & Updates" application, and by selecting the NVIDIA driver from the "Additional Drivers" tab.


(Answer: Continue installation)
ERROR: The Nouveau kernel driver is currently in use by your system.  This driver is incompatible with the NVIDIA driver, and must be disabled before proceeding.  Please consult the NVIDIA driver README and your Linux distribution's documentation for details on how to correctly disable the Nouveau kernel driver.
-> For some distributions, Nouveau can be disabled by adding a file in the modprobe configuration directory.  Would you like nvidia-installer to attempt to create this modprobe file for you? (Answer: No)
ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README available on the Linux driver download page at www.nvidia.com.

**Comment by PierreBeucher** [comment]
Odd, nouveau driver are specifically removed and blacklisted with a reboot... https://github.com/PierreBeucher/cloudypad/blob/master/ansible/roles/nvidia-driver/tasks/driver.yml#L2

Unless Paperspace does something funny with installed drivers. I observed a few times where installed package versions are updated by some kind of agent on their machine.

Will take a look

**Comment by mikaelmorvan** [comment]
I relaunched CloudyPad with the configure command

This time the nvidia driver installation was ok but the process seems to be staled on the next stage

Install linux-modules-extra package...

I waited for at list 5 min and nothing happens. I "ssh" on the VM and nothing is happening either when I htop the process.
I will kill the CloudyPad configure install and try to relaunch it once more time

**Comment by PierreBeucher** [comment]
> Install linux-modules-extra package...

Damn, people report lots of freeze on this one. It's a simple apt install but somehow it freezes... Will enquire as well.

**Comment by PierreBeucher** [comment]
Well, hopefully you won't have to restart the process thrice in the near future.

Be aware there's an issue on Wolf that may cause Steam to be stuck on network config: https://github.com/PierreBeucher/cloudypad/issues/52

**Comment by PierreBeucher** [comment]
Closing for now as latest release includes a few Paperspace fixes
