### ISSUE TITLE
Bug with ssh key encrypted with a passphrase

### ISSUE THREAD

**Issue by egrosner** [PierreBeucher/cloudypad#57]
The SSH key i want to use is encrypted with a passkey.

It looks like the library you are using has the option to pass a passkey in but throws an exception if one is not provided at code time.

`KeyEncryptedError: The OpenSSH format key (unnamed) is encrypted (password-protected), and no passphrase was provided in `options`
    at Object.readSSHPrivate (/cloudypad/node_modules/sshpk/lib/formats/ssh-private.js:78:11)
    at Object.read (/cloudypad/node_modules/sshpk/lib/formats/pem.js:209:19)
    at Object.read (/cloudypad/node_modules/sshpk/lib/formats/ssh-private.js:26:14)
    at Key.parse (/cloudypad/node_modules/sshpk/lib/key.js:252:27)
    at parseSshPrivateKeyToPublic (/cloudypad/dist/src/tools/ssh.js:169:42)
    at parseSshPrivateKeyFileToPublic (/cloudypad/dist/src/tools/ssh.js:166:12)
    at AwsProvisioner.provision (/cloudypad/dist/src/providers/aws/provisioner.js:68:85)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AwsInstanceInitializer.runProvisioning (/cloudypad/dist/src/providers/aws/initializer.js:27:9)
    at AwsInstanceInitializer.initializeInstance (/cloudypad/dist/src/core/initializer.js:106:9) {
  format: 'OpenSSH',
  keyName: '(unnamed)'
}`

**Comment by PierreBeucher** [comment]
Indeed Cloudy Pad does not handle SSH key passphrase for now.

However you should be able to use ssh-agent ;)

Fix incoming anyway !

**Comment by egrosner** [comment]
Yeah I think the library sshpk doesn't seem to care about ssh-agent, which I do have my key set and loaded into with the passphrase.

**Comment by perler** [comment]
ok, I am missing something here. my ssh key is loaded with ssh-agent and is offered when creating an instance. but the error pops up anyway. I created another passwordless keypair but this one isn't offered (does it need to be loaded with ssh-agent?)

**Comment by PierreBeucher** [comment]
SSH key handling has to be improved, in its current state it has limitations: only keys under `$HOME/.ssh` are shown and they must not be protected by passphrase. 

@perler where is your new keypair located in machine? Alternatively you can use `cloudypad create aws --private-ssh-key <path>` flag to specify a custom key path

**Comment by perler** [comment]
ok, this is strange, the key is in `$HOME/.ssh` but is not offered when adding a new pad.. will try it with the command line option.

**Comment by PierreBeucher** [comment]
... and only files starting with `id_*` and not ending with `*.pub` are shown, what's the name of you key?

**Comment by perler** [comment]
haha, ok, yes, that's the problem, the key is simply named "cloudypad".  Which doesn't follow conventions, so it's more or less my fault. I changed the name, now it works (this part at least, don't have the time now to test the whole thing..)

**Comment by PierreBeucher** [comment]
Great, let me know
