### ISSUE TITLE
Paperspace NVIDIA driver bug

### ISSUE THREAD

**Issue by BranislavF** [PierreBeucher/cloudypad#61]
Hello,

I am trying to use cloudypad with Paperspace and facing some issues during the driver installation. 

```
Download NVIDIA driver installer...
  Test done | msg: OK (341725273 bytes)
Download NVIDIA driver SHA256 checksum...
  Test done | msg: OK (101 bytes)
Verify SHA256 checksum...
  Test done | stdout: NVIDIA-Linux-x86_64-535.183.01.run: OK
Install NVIDIA driver...
  Test failed | msg: non-zero return code | stdout: Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 535.183.01..............................................................................................                                                                                                                                                                           ..........................................................................................................................................................................                                                                                                                                                                           ..........................................................................................................................................................................                                                                                                                                                                           ..........................................................................................................................................................................                                                                                                                                                                           ..........................................................................................................................................................................                                                                                                                                                                           ..........................................................................................................................................................................                                                                                                                                                                           ........................................................................................................................................................................

Welcome to the NVIDIA Software Installer for Unix/Linux

Detected 8 CPUs online; setting concurrency level to 8.
Installing NVIDIA driver version 535.183.01.
An alternate method of installing the NVIDIA driver was detected. (This is usually a package provided by your distributor.) A driver installed via that method may integra                                                                                                                                                                           te better with your system than a driver installed by nvidia-installer.

Please review the message provided by the maintainer of this alternate installation method and decide how to proceed:

The NVIDIA driver provided by Ubuntu can be installed by launching the "Software & Updates" application, and by selecting the NVIDIA driver from the "Additional Drivers"                                                                                                                                                                            tab.


(Answer: Continue installation)
For some distributions, Nouveau can be disabled by adding a file in the modprobe configuration directory.  Would you like nvidia-installer to attempt to create this modpr                                                                                                                                                                           obe file for you? (Answer: No) | stderr:
ERROR: The Nouveau kernel driver is currently in use by your system.  This driver is incompatible with the NVIDIA driver, and must be disabled before proceeding.  Please                                                                                                                                                                            consult the NVIDIA driver README and your Linux distribution's documentation for details on how to correctly disable the Nouveau kernel driver.


ERROR: Installation has failed.  Please see the file '/var/log/nvidia-installer.log' for details.  You may find suggestions on fixing installation problems in the README                                                                                                                                                                            available on the Linux driver download page at www.nvidia.com.

- Play recap -
  Test                       : ok=30   changed=13   unreachable=0    failed=1    rescued=0    ignored=1
2024-10-14 15:21:34.765 ERROR   /dist/src/tools/ansible.js:18   AnsibleClient   Ansible run failure: {"status":2,"signal":null,"output":[null,null,null],"pid":18,"stdout"                                                                                                                                                                           :null,"stderr":null}
/cloudypad/dist/src/tools/ansible.js:19
            throw new Error(`Ansible run failed, exit code ${ansibleProcess.status}`);
                  ^

Error: Ansible run failed, exit code 2
    at AnsibleClient.runAnsible (/cloudypad/dist/src/tools/ansible.js:19:19)
    at AnsibleConfigurator.configure (/cloudypad/dist/src/configurators/ansible.js:79:23)
    at PaperspaceInstanceInitializer.runConfiguration (/cloudypad/dist/src/core/initializer.js:67:28)
    at PaperspaceInstanceInitializer.initializeInstance (/cloudypad/dist/src/core/initializer.js:109:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.16.0

``` 

I can provide more details if needed,

Thanks

**Comment by PierreBeucher** [comment]
Probably a duplicate of https://github.com/PierreBeucher/cloudypad/issues/56

This a kinda known issue with Paperspace - despite specifically uninstalling Nouveau drivers before installing Nvidia ones, Nouveau drivers are somehow installed again. Paperspace had some kind of local agent on their machines which I suspect performs updates and such without our control, making it difficult to have something stable. I'm considering deprecating this provider as it's not the only odd behavior bug that may appear.

In the meantime you can try running `cloudypad configure` again on your instance

**Comment by BranislavF** [comment]
When I choose the P6000 i did not have any issues at all. But thanks for pointing it out.. Apart from that, the performance of Wolf is quite bad, Especially in higher resolutions (>2K). I would say that it needs to be replaced with something else. Maybe this one :https://github.com/selkies-project/docker-nvidia-glx-desktop

**Comment by PierreBeucher** [comment]
Are you sure this is because of Wolf, and not latency issue or CPU/RAM limitations ? Maybe it's caused by Wolf, but if you can give more context we can try to narrow it down. Which game are you running?

**Comment by BranislavF** [comment]
I am nearly 100% sure that Wolf has some performance penalty here. I tried again to use cloudypad to do all the configuration  (Paperspace P5000) with drivers, docker etc... and then run the GLX Desktop (from the link above) and the performance gap was really significant. Moreover, wolf is just a Steam container + Lutris. But GLX Desktop has the whole linux desktop and the ability to install anything when running privileged, and accessible from web browser :)

**Comment by PierreBeucher** [comment]
I see, thanks. Selkis has been on my watch list for some time, i actually considered it between Wolf and Sunshine for the main gaming server.

Cloudy Pad is designed to eventually support multiple server tools, so I'll give it a try soon :)

**Comment by BranislavF** [comment]
Great, thank you very much, that was a suggestion, users should be able to choose between Wolf and Selkies.

**Comment by PierreBeucher** [comment]
Yup that's what I meant

> Cloudy Pad is designed to eventually support multiple server tools

**Comment by BranislavF** [comment]
Anyway, the Paperspace issue can be closed, P5000 is working well. An issue already exists for the others.

Thanks for the quick tip.
