### ISSUE TITLE
Cannot delete cloudypad instance

### ISSUE THREAD

**Issue by saxlamen** [PierreBeucher/cloudypad#86]
When I tried to delete the instance created before when I had the installation issue with raspberrypi (ARM64):
cloudypad destroy test

It fails with below message:
2024-12-28 06:04:49.698 ERROR   /dist/src/core/state/migrator.js:184    StateMigrator   
 Error  Missing SSH config in state. Was instance fully configured ?
error stack:
  • migrator.js StateMigrator.migrateStateV0toV1
        /dist/src/core/state/migrator.js:21
  • manager.js  StateManager.loadInstanceStateSafe
        /dist/src/core/state/manager.js:163
  • manager-builder.js  InstanceManagerBuilder.buildManagerForInstance
        /dist/src/core/manager-builder.js:28
  • index.js    Command.<anonymous>
        /dist/src/index.js:141
Error destroying instance test: Error: Unable to migrate State from V0 to V1. Please create an issue with full error log and state: {"name":"test","ssh":{"privateKeyPath":"","user":"ubuntu"},"status":{"initalized":false,"configuration":{"configured":false},"provision":{"provisioned":false}},"provider":{"azure":{"provisionArgs":{"create":{"diskSize":100,"vmSize":"Standard_NC6s_v3","publicIpType":"dynamic","location":"eastasia","subscriptionId":"30902a81-f16c-40f8-8a22-44a8f197e21b","useSpot":true}}}}}
    at StateMigrator.migrateStateV0toV1 (/cloudypad/dist/src/core/state/migrator.js:185:19)
    at StateManager.loadInstanceStateSafe (/cloudypad/dist/src/core/state/manager.js:163:63)
    at InstanceManagerBuilder.buildManagerForInstance (/cloudypad/dist/src/core/manager-builder.js:28:23)
    at Command.<anonymous> (/cloudypad/dist/src/index.js:141:19)

**Comment by PierreBeucher** [comment]
This is caused by recent migration to a new state format from which "failed" instance like yours can't be translated into. (in your specific situation the instance never started provisioning so in fact does no exists considering new state format)

You can remove instance state directly by deleting folder `$HOME/.cloudypad/instances/test/`
